export const countriesInfo = [
	{
		id: 1,
		name: 'Kenya',
		officialName: 'Republic of Kenya',
		regime: 'Republic',
		headOfState: 'H.E Uhuru Kenyatta',
		area: '580 367 km²',
		capital: 'Nairobi',
		mainCities: [
			'Nairobie',
			'Mombasa',
			'Kisumu',
			'Eldoret',
			'Nyeri',
			'Meru',
			'Embu',
		],
		officialLanguage: ['English', 'Swahili'],
		localLanguages: ['Swahili and 40+ others languages'],
		currency: 'Kenyan Shilling -- 1 EUR= 132,67 KES (Janvier 2020)',
		nationalDay: 'December 12',
		population: '53,8 millions (ONU, 2020)',
		density: '85,3 habitants/km²',
		populationGrowth: '2,3%',
		lifeExpectacy: '66,2 years',
		literacyRate: '87,8% (Banque Mondiale, 2018)',
		indexOfDev: '0,579 -- 185e of 228 (2018)',
		religions: [
			'Protestants 45 % ',
			'Catholics 33 % ',
			'Musulmans 10 %',
			'Animistes 10 % ',
			'autres 2 %',
		],
		djibInCountry: {
			ambassador: 'H.E Yaçin Elmi Bouh',
			tel: '254 20 21 22 859',
			fax: ' 254 20 23 13 120',
			adress: `International House, 2nd Floor, Mama Nigima street
            P.O Box 34 446`,
			email: '',
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 2,
		name: 'Ethiopia',
		officialName: 'Federal Democratic Republic of Ethiopia',
		regime: ' Federal Republic',
		headOfState: 'H.E Abiy Ahmed Ali',
		area: '1 104 300 km²',
		capital: 'Addis Abeba',
		mainCities: [
			'Addis Abeba',
			'Debre Zeit',
			'Nazareth',
			'Baher Dar',
			'Dire Dawa',
			'Mekele',
		],
		officialLanguage: ['Amharic', 'English'],
		localLanguages: [
			'amharic, oromo, tigrinya, somali, gurage, sidamo, hadiyya, arabic',
		],
		currency: 'Ethiopian Birr -- 1 EUR= 46,6 ETB (December 2020)',
		nationalDay: 'Mai 28',
		population: '108 millions (ONU, 2018)',
		density: '96,2 inhabitants/km²',
		populationGrowth: '2,8%',
		lifeExpectacy: '65 years',
		literacyRate: '39% (Banque Mondiale, 2018)',
		indexOfDev: '0,463 -- 211e of 228 (2019)',
		religions: [
			'Protestants 18.6 % ',
			'Catholics 0.7 % ',
			'Musulmans 33.9 %',
			'Animistes 2.6 % ',
			'Orthodoxes 43.5 %',
		],
		djibInCountry: {
			ambassador: 'H.E Mohamed Idriss Farah',
			firsAdviser: 'Mr Abdi Mahamoud Eybe',
			tel: '251 116 61 32 00 / 61 30 06 / 63 20 85',
			fax: ' 254 20 23 13 120',
			adress: `Bolé Road near the breach 
            B.P: 1022`,
			email: 'mohamed.idriss@diplomatie.gouv.dj',
			consul: {
				name: 'H.E Aden Moussa Arreh',
				consulTitle: 'Consul Général de Djibouti à Dire Dawa',
				tel: '00251928186345',
				viceConsul: {
					name: 'Dire Dawa',
					tel: '251 251 11 22 21',
					fax: '251 251 11 00 96',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Birhanu Tsegaye',
			tel: '21 35 07 18',
			fax: '21 35 54 20',
			adress: '',
			email: '',
		},
	},
	{
		id: 3,
		name: 'Russia',
		officialName: 'Russian Federation',
		regime: ' Federal Republic',
		headOfState: 'H.E Vladimir Poutine',
		area: '17 100 00 km²',
		capital: 'Moscow',
		mainCities: [
			'Saint-Pétersbourg',
			'Novossibirsk',
			'Ekaterinbourg',
		],
		officialLanguage: ['Russian'],
		localLanguages: ['russian'],
		currency: 'Ruble -- 1 EUR= 90,04 ETB (May 2021)',
		nationalDay: 'June 12',
		population: '146,7 millions (ONU, 2018)',
		density: '8.56 inhabitants/km²',
		populationGrowth: '-0.01% (RosStat, 2020)',
		lifeExpectacy: '73,3 years',
		literacyRate: '100% (Banque Mondiale, 2018)',
		indexOfDev: '0,824 -- 71e of 228 (2019)',
		religions: [
			'Hindus 0.5 % ',
			'Christians 4.1 % ',
			'Musulmans 6.9 %',
			'Buddhists 0.5 % ',
			'Orthodoxes 41 %',
		],
		djibInCountry: {
			ambassador: ` H.E Dr Mohamed Ali Kamil
            `,
			firsAdviser: 'M Isse Abdillahi',
			tel: '007495 7821057',
			fax: ' 007495 7821059',
			adress: `127006 Moscou, Russia
            Sadovaya-Triumfalnaya Ulista, 4-10, Floor 3
            `,
			email: 'mohamed.kamil@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Mikhail Golovanov',
			tel: '21 35 07 40',
			fax: '21 35 59 90',
			adress: '',
			email: '',
		},
	},
	{
		id: 4,
		name: 'Belgium',
		officialName: 'kingdom of Belgium',
		regime: 'Federal state - constitutional monarchy',
		headOfState: 'H.E  Alexander De Croo ',
		area: '38 688 km²',
		capital: 'Brussels',
		mainCities: ['Anvers', 'Gand', 'Charleroi', 'Liège'],
		officialLanguage: ['Russian'],
		localLanguages: ['russian'],
		currency: 'euro -- ',
		nationalDay: 'July 21',
		population: '11 476 279 (Januari 1 2020)',
		density: '372.5 inhabitants/km²',
		populationGrowth: '0.49% / year (2019)',
		lifeExpectacy: '81.4 years',
		literacyRate: '99% (Banque Mondiale, 2018)',
		indexOfDev: '0,916 -- 26e of 228 (2019)',
		religions: [
			'Catholics 81 % ',

			'Musulmans 400 000',
			'Protestants 250 000 ',
			'Juifs 12 000',
		],
		djibInCountry: {
			ambassador: ` H.E Dr Omar Abdi Said
            `,
			firsAdviser: 'M Isse Abdillahi',
			tel: '322 347 69 67 / 347 69 61',
			fax: '322 347 69 63',
			adress: `
            Avenue Brugman 410
            1180 Bruxelles AV des Gémeaux, 13 1410 Waterloo
            `,
			email: 'omar.abdi@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 5,
		name: 'E.A.U',
		officialName: 'United Arab Emirates State',
		regime: 'Federation of Emirates',
		headOfState: ' Cheikh Khalifa Bin Zayed Al Nahyan',
		area: '82 880 km²',
		capital: 'Abu Dhabi',
		mainCities: ['Abu Dhabi', 'Dubai', 'Sharjah'],
		officialLanguage: ['arabe'],
		localLanguages: ['arabe'],
		currency: 'UAE dirham -- ',
		nationalDay: 'December 2',
		population: '9.8 million in 2020 (11.5 of nationals)',
		density: '83.6 inhabitants/km²',
		populationGrowth: '1.4% / year (2019)',
		lifeExpectacy: '77.81 years',
		literacyRate: '93% (Banque Mondiale, 2018)',
		indexOfDev: '0,83 -- 31e of 228 (2019)',
		religions: ['Musulmans 75%', 'Christians 13%', 'Others 12%'],
		djibInCountry: {
			ambassador: ` H.E  Osman Moussa Darar
            `,
			firsAdviser: 'M Abdoulakder Aden Ali',
			tel: '971 2 633 01 60 / 2 633 01 61',
			fax: ' 971 26 33 01 67',
			adress: `
            94340 Ryadh 11693
            `,
			email: 'osman.moussa@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Salim Al-,chamissi',
			tel: '21 35 32 21 / 21323303',
			fax: '21 35 33 32 ',
			adress: '',
			email: '',
		},
	},
	{
		id: 6,
		name: 'China',
		officialName: `People's Republic of China`,
		regime: 'Republic',
		headOfState: 'President XI Jinping',
		area: '9 562 911 km²',
		capital: 'Pékin',
		mainCities: [
			'Shanghai',
			'Canton',
			'Tianjin',
			'Chongqing',
			'Shenzhen',
			'Wuhan',
			'Chengdu',
			'Shenyang',
		],
		officialLanguage: ['chinese'],
		localLanguages: ['chinese, mandarin'],
		currency: 'Chinese Yuan -- ',
		nationalDay: 'October 1',
		population: '1.386 billion',
		density: '148 inhabitants/km²',
		populationGrowth: '0.6% / year (2019)',
		lifeExpectacy: '76 years',
		literacyRate: '96% (Banque Mondiale, 2018)',
		indexOfDev: '0,752 -- 86e of 228 (2017)',
		religions: ['Musulims', 'Christians ', 'taoism'],
		djibInCountry: {
			ambassador: ` H.E Abdallah Abdillahi Miguil
            `,
			firsAdviser: 'M Ismail Mohamed Djama Elabe',
			tel: ' 86 10 65 32 78 57 / 10 64 64 99 52',
			fax: ' 10 65 32 78 58',
			adress: `
            R.Tayuan B9-1-111

            Choyang Beijing, Office : Tayu 2-2-102
            `,
			email: ' abdallah.abdillahi@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E  Zhuo Ruisheng , ',
			tel: '21 35 22 47',
			fax: '21 35 48 33',
			adress: '',
			email: '',
		},
	},
	{
		id: 7,
		name: 'Netherland',
		officialName: 'Kingdom of the Netherlands',
		regime: 'Constitutional monarchy with parliamentary system',
		headOfState: 'H.E Mark Rutte ',
		area: '33 690 km²',
		capital: 'Amsterdam',
		mainCities: [
			'Amsterdam',
			'Rotterdam',
			'La Haye',
			'Utrecht',
			'Eindhoven',
		],
		officialLanguage: ['dutch'],
		localLanguages: ['dutch'],
		currency: 'euro -- ',
		nationalDay: 'April 27',
		population: '17.2  (Januari 1 2020)',
		density: '405,1 inhabitants/km²',
		populationGrowth: '0.4% / year (2015)',
		lifeExpectacy: '79.9 years for men and 83.3 for women',
		literacyRate: '99% (Banque Mondiale, 2018)',
		indexOfDev: '0,921 -- 4e of 228 (2019)',
		religions: [
			'Catholics 27% ',
			'Musulmans 7%',
			'Protestants 17% ',
			'Others 4%',
		],
		djibInCountry: {
			ambassador: ` H.E Dr Omar Abdi Said
            `,
			firsAdviser: 'M Isse Abdillahi',
			tel: '322 347 69 67 / 347 69 61',
			fax: '322 347 69 63',
			adress: `
            Avenue Brugman 410
            1180 Bruxelles AV des Gémeaux, 13 1410 Waterloo
            `,
			email: 'omar.abdi@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 8,
		name: 'Luxemburg',
		officialName: 'Grand Duchy of Luxembourg',
		regime: 'Constitutional monarchy',
		headOfState: 'H.E Xavier Bettel  ',
		area: '2.586 km²',
		capital: 'Luxembourg-City',
		mainCities: ['Luxembourg', ' Esch-sur-Alzette'],
		officialLanguage: ['luxembourgeois', 'french', 'dutch'],
		localLanguages: ['luxembourgeois', 'french', 'dutch'],
		currency: 'euro -- ',
		nationalDay: 'June 23',
		population: '602.005 in 2020 (46% of foreigners)',
		density: '222.8 inhabitants/km²',
		populationGrowth: '2.4% / year ',
		lifeExpectacy: '82.2 years',
		literacyRate: '99% (Banque Mondiale, 2018)',
		indexOfDev: '0,892 -- 19e of 228 (2019)',
		religions: ['Catholics 90% '],
		djibInCountry: {
			ambassador: ` H.E Dr Omar Abdi Said
            `,
			firsAdviser: 'M Isse Abdillahi',
			tel: '322 347 69 67 / 347 69 61',
			fax: '322 347 69 63',
			adress: `
            Avenue Brugman 410
            1180 Bruxelles AV des Gémeaux, 13 1410 Waterloo
            `,
			email: 'omar.abdi@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 9,
		name: 'Egypt',
		officialName: 'Arab Republic of Egypt',
		regime: 'Republic',
		headOfState: 'H.E  Abdel Fattah Al Sissi ',
		area: '1 002 000 km²',
		capital: 'Le caire',
		mainCities: [
			'Alexandrie',
			'Port-Saïd',
			'Assiout',
			'Louxor',
			'Assouan',
		],
		officialLanguage: ['arabe'],
		localLanguages: ['arabe'],
		currency: 'egyptian pound -- ',
		nationalDay: 'July 23',
		population: '100,4 million in 2020 (46% of foreigners)',
		density: '83 inhabitants/km²',
		populationGrowth: '2% / year ',
		lifeExpectacy: '71.8 years',
		literacyRate: '80.8% (Banque Mondiale, 2018)',
		indexOfDev: '0,69',
		religions: ['Muslims 90% ', 'Christians 10%'],
		djibInCountry: {
			ambassador: ` H.E Mohamed Douhour Hersi
            `,
			firsAdviser: 'M Isse Abdillahi',
			tel: '202333 66 435 / 333 66 434',
			fax: '202 333 66 437',
			adress: `
            15, Rue Docteur Mohamed Abdou El Said
            (Ex Hayet El Tadris) - Dokki
            `,
			email: 'mohamed.douhour@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Dr Mohamed Moustapha Oufi, Ambassadeur',
			tel: '21 35 82 84 / 21 35 82 98 /21 35 82 91',
			fax: '21 35 82 99',
			adress: '',
			email: '',
		},
	},
	{
		id: 10,
		name: 'Eritrea',
		officialName: 'State of Eritrea',
		regime: 'Republic',
		headOfState: 'H.E Issayas Afwerki ',
		area: '117 600 km²',
		capital: 'Asmara',
		mainCities: ['Asmara', 'Massaoua', 'Assab', 'Keren'],
		officialLanguage: ['tigrinya', 'arabe', 'english'],
		localLanguages: [
			'tigrinya',
			'arabe',
			'tigré',
			'kunama',
			'afar',
			'bilen',
			'saho',
			'nara',
		],
		currency: 'Nakfa -- ',
		nationalDay: 'May 24',
		population: 'No data',
		density: 'No data',
		populationGrowth: 'No data',
		lifeExpectacy: '65 years',
		literacyRate: 'No data',
		indexOfDev: '0,442 - 179e of 187 (2018)',
		religions: [
			'Muslims 50% ',
			'Orthodox 30%, Catholics 13%',
			'Others 7%',
		],
		djibInCountry: {
			ambassador: ` H.E Mohamed Douhour Hersi
            `,
			firsAdviser: 'M Isse Abdillahi',
			tel: ' 291-1-111620 / 291-1-111621',
			fax: '291-1-111622',
			adress: `
            ZERAYAKOB STREET , GEJERET NE ESHTEY
            ASMARA
            PO Box : 7702
            `,
			email: 'aden.ali@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 11,
		name: 'France',
		officialName: 'Republic of France',
		regime: 'Republic',
		headOfState: 'H.E Emmanuel Macron',
		area: '	640,679 km²',
		capital: 'Paris',
		mainCities: ['Paris', 'Lyon', 'Lille', 'Marseille', 'Bordeaux'],
		officialLanguage: ['french'],
		localLanguages: ['french'],
		currency: 'Euro -- ',
		nationalDay: 'July 14',
		population: '67,413,000 (May 2021 estimate)',
		density: '104 inhabitants/km²',
		populationGrowth: '0.1%',
		lifeExpectacy: '82 years',
		literacyRate: '99%',
		indexOfDev: '0,901 - 26e of 189 (2018)',
		religions: [
			'Christiants 51%',
			'Muslims 5% ',
			'No religion 40%',
			'Others 3%',
			'Undeclared 1%',
		],
		djibInCountry: {
			ambassador: ` H.E Ayeid Mousseid Yahya
            `,
			firsAdviser: 'M Mourad Houssein Mouti',
			tel: '33 1 47 27 49 22 / 47 27 43 49',
			fax: ' 33 1 45 53 50 53',
			adress: `
            26, Rue Emile Menier 75 116 Paris
            `,
			email: 'ayeid.mousseid@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Arnaud Guillois',
			tel: ' 21 35 09 63',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 12,
		name: 'India',
		officialName: 'Republic of India',
		regime: 'Federal republic',
		headOfState: 'H.E  Narendra Mod',
		area: '3 287 263 km²',
		capital: 'New Delhi',
		mainCities: [
			'Delhi',
			'Mumbai',
			'Kolkata',
			'Chennai',
			'Bangalore',
		],
		officialLanguage: [
			'english',
			'hindi',
			'there are 22 constitutional languages',
		],
		localLanguages: [''],
		currency: 'Euro -- ',
		nationalDay: 'July 14',
		population: '1 billion 366 millions (World bank 2019)',
		density: '455 inhabitants/km² (World bank 2019)',
		populationGrowth: '1.1% (World bank 2019)',
		lifeExpectacy: '69.4 years (World bank 2019)',
		literacyRate: '74.4% (World bank 2019)',
		indexOfDev: '0,624 - 130e of 189 (2018)',
		religions: [
			'Hindus 79.8%',
			'Muslims 14.2% ',
			'Christians 2.3%',
			'Sikhism 1.7%',
			'Jainism 0.4%',
		],
		djibInCountry: {
			ambassador: ` H.E Said Absieh Warsame
            `,
			firsAdviser: 'M Mahamoud Abdillahi',
			tel: '91 11 41 35 44 91/92/93',
			fax: '11 41 35 44 90',
			adress: `
            A2/20 Safdarjung Enclave
            New-Delhi – 110029 Inde
            `,
			email: 'said.absieh@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 13,
		name: 'Morocco',
		officialName: 'Kingdom of Morocco',
		regime: 'Monarchy',
		headOfState: 'King Mohammed VI ',
		area: '446.550 km²',
		capital: 'Rabat',
		mainCities: [
			'Casablanca',
			'Fès',
			'Tanger',
			'Meknès',
			'Marrakech',
		],
		officialLanguage: ['arabic', 'tamazight'],
		localLanguages: ['darija', 'berber languages', 'french'],
		currency: 'dirham marocain -- ',
		nationalDay: 'July 30',
		population: '36.9 millions (World bank 2019)',
		density: '79 inhabitants/km² (World bank 2019)',
		populationGrowth: '1.3% (World bank 2019)',
		lifeExpectacy: '77 years (World bank 2019)',
		literacyRate: '73.8% (World bank 2019)',
		indexOfDev: '0,686 - 121e of 189 (2018)',
		religions: ['Muslims 99% ', 'Christians and judaism 1%'],
		djibInCountry: {
			ambassador: ` H.E Ibrahim Bileh Doualeh
            `,
			firsAdviser: 'M Chehem Ibrahim Chehem',
			tel: '212 662 22 66 29 69',
			fax: ' 212 537 754 900',
			adress: `
            28, Rue Bani Boufrah-Lotissement Chandouri-Souissi - Rabat
            `,
			email: 'ibrahim.billeh@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: ' Moubarak hadawi ',
			tel: ' 77 03 37 10',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 14,
		name: 'Sudan',
		officialName: 'Republic of Sudan',
		regime: 'Federal government',
		headOfState:
			'H.E Abdelfattah al-Burhan (Political transition underway since August 17, 2019) ',
		area: '1.88 million km²',
		capital: 'Khartoum',
		mainCities: [
			'Omdurman',
			'Port-Soudan',
			'Nyala',
			'Wad Medani',
			' El Obeid',
		],
		officialLanguage: ['arabic'],
		localLanguages: [
			'arabic',
			'english',
			'more than 100 languages',
		],
		currency: 'Sudanese pound -- ',
		nationalDay: 'Januari 1',
		population: '42.81 millions (World bank 2019)',
		density: '23.7 inhabitants/km² (World bank 2019)',
		populationGrowth: '+2.4% (World bank 2019)',
		lifeExpectacy: '65 years (World bank 2019)',
		literacyRate: '51% (World bank 2019)',
		indexOfDev: '168e of 189 (2018)',
		religions: ['Muslims 96.7% ', 'Christians 3%'],
		djibInCountry: {
			ambassador: ` H.E Ahmed Ali Barreh
            `,
			firsAdviser: 'M Ali Elabe',
			tel: '249 1 83 25 19 52 / 25 19 50 / 52 77 28 ',
			fax: '249 1 83 25 19 60',
			adress: `
            11111, PO BOX : 12992
            `,
			email: 'ahmed.ali@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Hamza Al-amin Bao ',
			tel: '21 35 64 04',
			fax: ' 21 35 18 16',
			adress: '',
			email: '',
		},
	},
	{
		id: 15,
		name: 'Turkey',
		officialName: 'Republic of Turkey',
		regime: 'Republic',
		headOfState: 'H.E  Recep Tayyip ERDOĞAN ',
		area: '780 576  km²',
		capital: 'Ankara',
		mainCities: [
			'Istanbul',
			'Ankara',
			'Izmir',
			'Bursa',
			'Eskişehir',
		],
		officialLanguage: ['turkish'],
		localLanguages: ['turkish'],
		currency: 'Turkish pound -- ',
		nationalDay: 'October 29',
		population: '82 millions (World bank 2019)',
		density: '110 inhabitants/km² (World bank 2019)',
		populationGrowth: '1.47% (World bank 2019)',
		lifeExpectacy: '76.4 years (World bank 2019)',
		literacyRate: '95.7% (World bank 2017)',
		indexOfDev: '0.767,71e of 189 (2018)',
		religions: ['Muslims 99% ', 'Others 1%'],
		djibInCountry: {
			ambassador: ` H.E Aden Houssein Abdillahi
            `,
			firsAdviser: 'M Mouktar Mohamed Mohamoud',
			tel: '00 90 312 491 95 13 / 14',
			fax: ' 00 90 312 491 95 10',
			adress: `
            Galip Erdem Caddesi, 613. Sok,
            N°6 Yildiz – çankaya - Ankara
            `,
			email: 'aden.houssein.abdillahi@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Salim Levent Sahinkaya ',
			tel: '21 35 12 90',
			fax: '21 35 12 92',
			adress: '',
			email: '',
		},
	},
	{
		id: 16,
		name: 'Yemen',
		officialName: 'Republic of Yemen',
		regime: 'Republic',
		headOfState: 'H.E Abd Rabbo Mansour Hadi ',
		area: '527 970 km²',
		capital: 'Sanaa',
		mainCities: ['Sanaa', 'Aden', 'Taez', 'Hodeida', 'Mukalla'],
		officialLanguage: ['arabic'],
		localLanguages: ['arabic'],
		currency: 'Yemeni Riyal -- ',
		nationalDay: 'May 22',
		population: '26.94 millions (Worldometer 2020)',
		density: '68.94 inhabitants/km² (World bank 2019)',
		populationGrowth: '2.64% (World bank 2019)',
		lifeExpectacy: '65 years (World bank 2019)',
		literacyRate: '85% (World bank 2017)',
		indexOfDev: '0.463, 215e (PNUD 2018)',
		religions: ['Muslims sunnite 70% ', 'Muslims chiite 30%'],
		djibInCountry: {
			ambassador: ` 
            `,
			firsAdviser: '',
			tel: '',
			fax: ' ',
			adress: `
            `,
			email: '',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Abdallah Bin-moussalam Al-sukatre ',
			tel: '21 35 29 75',
			fax: '21 35 66 80',
			adress: '',
			email: '',
		},
	},
	{
		id: 17,
		name: 'USA',
		officialName: 'United States of America',
		regime: 'Federal republic',
		headOfState: 'H.E Joseph Robinette Biden Jr',
		area: ' 9 363 123 km²',
		capital: 'Washington D.C',
		mainCities: ['New York', 'Los Angeles', 'Chicago'],
		officialLanguage: ['english'],
		localLanguages: ['english'],
		currency: 'American dollar -- ',
		nationalDay: 'July 4',
		population: '329 millions (US Census 2020)',
		density: '32 inhabitants/km² ',
		populationGrowth: '1% ',
		lifeExpectacy: '76 years for men and 81 for women ',
		literacyRate: '97% ',
		indexOfDev: '0.92 , 15e (PNUD 2019)',
		religions: [
			'Protestants 47% ',
			'Catholics 21%',
			'Jews 1.9',
			'Muslims 0.9%',
		],
		djibInCountry: {
			ambassador: ` H.E Mohamed Siad Doualeh
            `,
			firsAdviser: 'M Youssouf Aden Moussa',
			tel: '(12 12) 753 31 63 / 319 39 25',
			fax: '(12 12) 223 12 76 ',
			adress: `
            10 River Raod APT, 2F New-York, NY 10044
            `,
			email: 'mohamed.siad@diplomatie.gouv.dj',
			consul: {
				name: 'M Issa Daher',
				consulTitle: '',
				tel: ' 12 02 331 02 70 / 331 02 65',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Jonathan Goodale Pratt ',
			tel: '21 45 30 00',
			fax: '21 45 31 29',
			adress: '',
			email: '',
		},
	},
	{
		id: 18,
		name: 'Switzerland',
		officialName: 'Swiss Confederation',
		regime: 'Federal state - semi-direct democracy',
		headOfState: 'H.E Guy Parmelin',
		area: '  41 285 km²',
		capital: 'Berne ',
		mainCities: ['Zurich', 'Genève', 'Bâle', 'Lausanne'],
		officialLanguage: ['german', 'french', 'italian', 'romanche'],
		localLanguages: ['german', 'french', 'italian'],
		currency: 'Swiss franc -- ',
		nationalDay: 'August 1',
		population: '8.7 millions (source: Federal Statistical Office)',
		density:
			'206.53 inhabitants/km² (source: Federal Statistical Office 2018) ',
		populationGrowth: '0.7% ',
		lifeExpectacy: '81.9 years for men and 85.6 for women ',
		literacyRate: '99.6%',
		indexOfDev: '0.955 , 2e (PNUD 2019)',
		religions: [
			'Protestants 26.9% ',
			'Catholics 34%',
			'Jews 0.2',
			'Muslims 5.5%',
			'Other christians 5.7',
			'atheist 26.3',
			' Others 7.4%',
		],
		djibInCountry: {
			ambassador: ` H.E Kadra Ahmed Hassan
            `,
			firsAdviser: 'M Houmed-Gaba Maki Houmed Gaba',
			tel: '41 22 749 10 90',
			fax: '41 22 749 10 91',
			adress: `
            10 River Raod APT, 2F New-York, NY 10044
            `,
			email: 'kadra.ahmed@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: '',
			tel: '',
			fax: '',
			adress: '',
			email: '',
		},
	},
	{
		id: 19,
		name: 'Germany',
		officialName: 'Federal Republic of Germany',
		regime: 'Parliamentary democracy',
		headOfState: 'H.E Angela Merkel',
		area: '357 027 km²',
		capital: 'Berlin',
		mainCities: ['Hambourg', 'Munich', 'Cologne', 'Stuttgart'],
		officialLanguage: ['german'],
		localLanguages: ['german'],
		currency: 'Euro -- ',
		nationalDay: 'October 3',
		population: '83.15 millions',
		density: '233.56 inhabitants/km²',
		populationGrowth: '0.2% ',
		lifeExpectacy: '80.89 years ',
		literacyRate: '99%',
		indexOfDev: '0.947 ',
		religions: [
			'Christianity 55%',
			'Muslims 6.5%',
			'atheist 37.7%',
			' Others 0.8%',
		],
		djibInCountry: {
			ambassador: ` H.E Aden Mohamed Dileita
            `,
			firsAdviser: 'M Mohamed Osman Chireh',
			tel: '49 30 26 39 01 57',
			fax: '49 30 26 93 41 65',
			adress: `
            Kurfûrstenstrabe 84-107 87 Berlin
            `,
			email: 'aden.dileita@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Michael Häusler',
			tel: '21 34 40 24',
			fax: ' 21 34 24 79',
			adress: '',
			email: '',
		},
	},
	{
		id: 20,
		name: 'Cuba',
		officialName: 'Republic of Cuba',
		regime: 'one-party socialist regime',
		headOfState: 'H.E  Miguel Díaz-Canel',
		area: '106 449 km²',
		capital: 'La Havane',
		mainCities: [
			'Santiago de Cuba',
			'Villa Clara',
			'Holguín',
			'Camagüey',
		],
		officialLanguage: ['spanish'],
		localLanguages: ['spanish'],
		currency: 'Cuban peso -- ',
		nationalDay: 'Januari 1',
		population: '11 333 483 ',
		density: '102.3 inhabitants/km²',
		populationGrowth: '0.32% ',
		lifeExpectacy: '78.7 years ',
		literacyRate: '99.8%',
		indexOfDev: '0.783 -- 70e (PNUD 2019) ',
		religions: ['Catholics 10%'],
		djibInCountry: {
			ambassador: ` H.E Nasser Mohamed Ousbo
            `,
			firsAdviser: 'M Mohamed Osman Chireh',
			tel: '(+53) 7- 207 9000 or (+53) 7- 207 9001',
			fax: '49 30 26 93 41 65',
			adress: `
            Calle 22, esq. a 7ma, No. 518, Miramar, Playa,
            La Habana P.O. Box: 503
            `,
			email: 'nasser.mohamed@diplomatie.gouv.dj',
			consul: {
				name: 'Mounawar Ali Mohamed',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '(+53) 7- 207 76 67 / (+53) 7- 214 09 15',
					fax: '(+53) 7- 207 96 23',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Lázaro Leslie Polledo Mesa',
			tel: ' 21 34 06 71/ 34 06 42',
			fax: ' 21 34 06 25',
			adress: '',
			email: '',
		},
	},
	{
		id: 21,
		name: 'Japon',
		officialName: 'Japon',
		regime: 'Parliamentary monarchy',
		headOfState: 'H.E Yoshihide SUGA',
		area: '377 000 km²',
		capital: 'Tokyo',
		mainCities: ['Sapporo', 'Yokohama', 'Nagoya', 'Osaka'],
		officialLanguage: ['japanese'],
		localLanguages: ['japanese'],
		currency: 'Yen -- ',
		nationalDay: 'Februari 23',
		population: '125,988 millions ',
		density: '334 inhabitants/km²',
		populationGrowth: '-0.15% ',
		lifeExpectacy: '84.21 years ',
		literacyRate: '100%',
		indexOfDev: '0.915 -- 28e (PNUD 2018) ',
		religions: ['shintoïsm', 'buddhism'],
		djibInCountry: {
			ambassador: ` H.E Ahmed Araita Ali
            `,
			firsAdviser: 'M Ismael Youssouf Hirsi',
			tel: '813 57 04 06 82',
			fax: '813 57 25 83 05',
			adress: `
            5-18-10 Shimomeguro, Meguro-ku
            Tokyo 153-0064 JAPON
            `,
			email: 'nasser.mohamed@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Omio Otsuka',
			tel: '21 35 49 81',
			fax: '21 35 71 35',
			adress: '',
			email: '',
		},
	},
	{
		id: 22,
		name: 'SaudiArabia',
		officialName: 'Kingdom of Saudi Arabia',
		regime: 'Monarchy',
		headOfState:
			'His Majesty King Salman bin Abdulaziz Al Saud, Guardian of the Two Holy Places',
		area: '2 253 000 km²',
		capital: 'Riyad',
		mainCities: ['Djeddah', 'Mecca', 'Medina', 'Dammam'],
		officialLanguage: ['arabic'],
		localLanguages: ['arabic'],
		currency: 'saudi riyal -- ',
		nationalDay: `September 23 `,
		population: '32.9 millions with 37% of foreigners (2019)',
		density: '15.3 inhabitants/km²',
		populationGrowth: '2% ',
		lifeExpectacy: '75 years ',
		literacyRate: '87%',
		indexOfDev: '0.847 -- 42e (PNUD 2016) ',
		religions: [
			`Islam (predominantly Sunni population, existence of a Shiite minority)`,
		],
		djibInCountry: {
			ambassador: ` H.E Dya-Eddine Said Bamakhrama
            `,
			firsAdviser: '',
			tel: '+966 11 454 3182 / +966 11 454 3583',
			fax: '+966 11 456 9168',
			adress: `
            5-18-10 Shimomeguro, Meguro-ku
            Tokyo 153-0064 JAPON
            `,
			email: 'dyaeddin.said@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Abdoula-aziz Al-matar',
			tel: '21 25 08 80 / 21 25 06 60 ',
			fax: '21 25 09 09',
			adress: '',
			email: '',
		},
	},
	{
		id: 23,
		name: 'Qatar',
		officialName: 'State of Qatar ',
		regime: 'Emirate',
		headOfState: 'Cheikh Tamim bin Hamad Al Thani',
		area: '11.571 km²',
		capital: 'Doha',
		mainCities: ['Al Wakrah', 'Al Khor', 'Al Rayyan', 'Mesaied'],
		officialLanguage: ['arabic'],
		localLanguages: ['arabic', 'english', 'urdu'],
		currency: 'qatari riyal -- ',
		nationalDay: `December 18`,
		population: '2.7 millions with 330 000 of citizens (2019)',
		density: '227.3 inhabitants/km²',
		populationGrowth: '2.7% ',
		lifeExpectacy: '78.3 years ',
		literacyRate: '97.8%',
		indexOfDev: '0.856 -- 37e (2017) ',
		religions: [`Muslims, Christians, Hindus, Buddhists`],
		djibInCountry: {
			ambassador: ` H.E Tayeb Doubad Robleh
            `,
			firsAdviser: 'Mrs Zahra Hassan Cheik',
			tel: ' 974 4 48 38 461 / 49 34 657',
			fax: '974 448 39 245',
			adress: `
            5-18-10 Shimomeguro, Meguro-ku
            Tokyo 153-0064 JAPON
            `,
			email: ' dayib.doubad@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Rachid Bin-salim',
			tel: '21 35 97 97 / 21 32 24 01 ',
			fax: '21 35 96 96',
			adress: '',
			email: '',
		},
	},
	{
		id: 24,
		name: 'Ethiopia',
		officialName: 'Federal Democratic Republic of Ethiopia ',
		regime: 'Federal Republic',
		headOfState: 'H.E  Abiy Ahmed Ali',
		area: '1 104 300  km²',
		capital: 'Addis Abeba',
		mainCities: [
			'Addis Abeba',
			'Debre Zeit',
			'Nazareth',
			'Baher Dar',
		],
		officialLanguage: ['amharic', 'english'],
		localLanguages: [
			'amharic',
			'oromo',
			'tigrinya',
			'somali',
			'gurage',
			'sidamo',
			'hadiyya',
			'arabic',
		],
		currency: 'ethiopian birr -- ',
		nationalDay: `May 28 `,
		population: '108 millions (2019)',
		density: '96.2 inhabitants/km²',
		populationGrowth: '2.8% ',
		lifeExpectacy: '65 years ',
		literacyRate: '39% (2017)',
		indexOfDev: '0.463 -- 211e (2017) ',
		religions: [
			'Orthodox 43.5%',
			' Muslims 33.9%',
			' Protestants 18.6%',
			' Animists 2.6%',
			'Catholics 0.7%',
			'others 0.7%',
		],
		djibInCountry: {
			ambassador: ` H.E Mohamed Idriss Farah
            `,
			firsAdviser: 'M Abdi Mahamoud Eybe',
			tel: ' 251 116 61 32 00 / 61 30 06 / 63 20 85',
			fax: '251 116 61 27 86',
			adress: `
            Bolé Road
            BP : 1022
            `,
			email: 'mohamed.idriss@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Birhanu Tsegaye,',
			tel: '21 35 07 18',
			fax: '21 35 54 20',
			adress: '',
			email: '',
		},
	},
    {
		id: 25,
		name: 'Somalia',
		officialName: 'Federal Republic of Somalia',
		regime: 'presidential, federal',
		headOfState: 'H.E Mohamed Abdullahi Mohamed (aka Farmajo)',
		area: '637 657  km²',
		capital: 'Mogadishu',
		mainCities: [
			'Mogadishu',
			'Hargeisa',
			'Bosasso',
			'Kismayo',
		],
		officialLanguage: ['somali', ],
		localLanguages: [
			'somali',
			'arabic',
			'english',
		],
		currency: 'Somali shilling -- ',
		nationalDay: `July 1`,
		population: '11.1 millions (2016)',
		density: '17.7 inhabitants/km²',
		populationGrowth: '2.9% (2019) ',
		lifeExpectacy: '56 years ',
		literacyRate: 'No data',
		indexOfDev: 'No data ',
		religions: [
			' Muslims 99%',
			
		],
		djibInCountry: {
			ambassador: ` H.E Aden Hassan Aden
            `,
			firsAdviser: 'M Sahal Abdi Aden',
			tel: '252 124 03 47',
			fax: '252 186 58 20',
			adress: `
         
            `,
			email: 'aden.hassan.aden@diplomatie.gouv.dj',
			consul: {
				name: '',
				consulTitle: '',
				tel: '',
				viceConsul: {
					name: '',
					tel: '',
					fax: '',
				},
			},
		},
		countryInDjib: {
			ambassador: 'H.E Salad Ali Jele',
			tel: '21 35 88 15',
			fax: '21 35 20 53',
			adress: '',
			email: '',
		},
	},
];
