export const countriesInfo = [
	{
		id: '1',
		name: 'Kenya',
		officicalName: 'Republic of Kenya',
		regime: 'Republic',
		headOfState: 'M.Uhuru Kenyatta',
		area: '580 367 km2',
		capital: 'Nairobi',
		mainCities: [
			'Nairobie',
			'Mombasa',
			'Kisumu',
			'Eldoret',
			'Nyeri',
			'Meru',
			'Embu',
		],
		officialLanguage: ['English', 'Swahili'],
		localLanguages: ['Swahili and 40+ others languages'],
		currency: 'Kenyan Shilling -- 1 EUR= 132,67 KES (Janvier 2020)',
		nationalDay: 'December 12',
		population: '53,8 millions (ONU, 2020)',
		density: '85,3 habitants/km2',
		populationGrowth: '2,3%',
		lifeExpectacy: '66,2 years',
		literacyRate: '87,8% (Banque Mondiale, 2018)',
		indexOfDev: '0,579 -- 185e of 228 (2018)',
		religions: [
			'Protestants 45 % ',
			'Catholiques 33 % ',
			'Musulmans 10 %',
			'Animistes 10 % ',
			'autres 2 %',
		],
		djibInCountry: {
			ambassador: 'S.E.M Yaçin Elmi Bouh',
			tel: '254 20 21 22 859',
			fax: ' 254 20 23 13 120',
			adress: `International House, 2nd Floor, Mama Nigima street
            P.O Box 34 446`,
			email: '',
		},
		countryInDjib: {
			ambassador: 'anonym',
			tel: 'anonym',
			fax: 'anonym',
			adress: 'anonym',
			email: 'anonym',
		},
	},
	{
		id: 2,
		name: 'Ethiopia',
		officicalName: 'Federal Democratic Republic of Ethiopia',
		regime: ' Federal Republic',
		headOfState: 'S.E.M Abiy Ahmed Ali',
		area: '1 104 300 km2',
		capital: 'Addis Abeba',
		mainCities: [
			'Addis Abeba',
			'Debre Zeit',
			'Nazareth',
			'Baher Dar',
			'Dire Dawa',
			'Mekele',
		],
		officialLanguage: ['Amharic', 'English'],
		localLanguages: [
			'amharic, oromo, tigrinya, somali, gurage, sidamo, hadiyya, arabic',
		],
		currency: 'Ethiopian Birr -- 1 EUR= 46,6 ETB (December 2020)',
		nationalDay: 'Mai 28',
		population: '108 millions (ONU, 2018)',
		density: '96,2 inhabitants/km2',
		populationGrowth: '2,8%',
		lifeExpectacy: '65 years',
		literacyRate: '39% (Banque Mondiale, 2018)',
		indexOfDev: '0,463 -- 211e of 228 (2019)',
		religions: [
			'Protestants 18.6 % ',
			'Catholiques 0.7 % ',
			'Musulmans 33.9 %',
			'Animistes 2.6 % ',
			'Orthodoxes 43.5 %',
		],
		djibInCountry: {
			ambassador: 'S.E.M Mohamed Idriss Farah',
			firsAdviser: 'Mr Abdi Mahamoud Eybe',
			tel: '251 116 61 32 00 / 61 30 06 / 63 20 85',
			fax: ' 254 20 23 13 120',
			adress: `Bolé Road near the breach 
            B.P: 1022`,
			email: 'mohamed.idriss@diplomatie.gouv.dj',
			consul: {
				name: 'S.E.M Aden Moussa Arreh',
				consulTitle: 'Consul Général de Djibouti à Dire Dawa',
				tel: '00251928186345',
				viceConsul: {
					name: 'Dire Dawa',
					tel: '251 251 11 22 21',
					fax: '251 251 11 00 96',
				},
			},
		},
		countryInDjib: {
			ambassador: 'S.E.M. Birhanu Tsegaye',
			tel: '21 35 07 18',
			fax: '21 35 54 20',
			adress: 'anonym',
			email: 'anonym',
		},
	},
];
